services:
  notifications-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgames-Notification
    ports:
      - "5056:5056"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5056"

      RabbitMq__HostName: "cloudgames-rabbitmq" 
      RabbitMq__Port: "5672"
      RabbitMq__UserName: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__ExchangeName: "cloudgames.topic"
      RabbitMq__QueueNameUserCreated: "UserCreatedEvent"
      RabbitMq__QueueNamePaymentProcessed: "PaymentProcessedEvent"

    networks:
      - cloudgames-network

networks:
  cloudgames-network:    
    external: true
